name: Deploy Hexo To COS & Github Pages

on:
push:
  braches: 
  - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/steup-node@v1
      with:
        node-version: "10.x"

    - name: Setup Hexo & COS env
      env:
        SecretId: ${{ secrets.SecretId }}
        SecretKey: ${{ secrets.SecretKey }}

      run: |
        npm install
        sed -i "s/SecretId/${SecretId}/" _config.yml
        sed -i "s/SecretKey/${SecretKey}/" _config.yml
    
    - name: Deploy to COS
      run: |
        hexo clean && hexo g && hexo d

    - name: Deploy to Github Pages
      env:
        GH_REF: github.com/myloft/blog
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
        
      run: |
        git clone https://${GH_REF} .deploy_git
        cd .deploy_git
        git checkout master
        cd ../
        mv .deploy_git/.git/ ./public/
        cd ./public
        git init
        git config user.name "Solyn"
        git config user.email "admin@iloft.xyz"
        git add .
        git commit -m ":memo:\ Update blog by Actions"
        git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:gh-pages